### ISSUE TITLE
Call sign

### ISSUE THREAD

**Issue by d3mac123** [ra1fh/airtraffic#6]
*** I know this is not related to your amazing code so, I will understand if you cannot help ***

I am new to GDL90 and am trying to code a small ESP32 board to read data from a Stratux and show it on the board display. I found an old code that shows how to extract basic info from a GDL90 dump. For example, to get the target heading:
`tHeading = (((int)messageBuffer[j + 18] & 0xFF)) * 360 / 256;`

All is good but I am having trouble capturing the call sign. I am doing:
`tCall = ((int)(messageBuffer[j + 20] & 0xFF)); //I looped it 8 times j+20 to 27`

and getting the following sequence (in this example N11EL - first traffic id):
`0 49 49 69 76 32 32 32`

I converted to ASCII but it does not read N11EL (just garbage). Any idea on how to capture the call sign properly?

Thanks!
Alex

**Comment by ra1fh** [comment]
When you interpret those bytes as decimal ASCII, you get:
```
.11EL...
```
Not sure why the leading 'N' is missing. 

What can happen though is that you get additional characters inserted into the message due to escaping. If there is a 0x7e or 0x7d in the original message, the sender will replace those by two bytes before sending (`0x7d 0x5d` or `0x7d 0x5e`). That would result in off-by-one or off-by-n if you don't take that into account when interpreting the message. If that has happened and your decoder doesn't do de-escaping, the leading `0` would actually be the emitter category and not part of the call sign.

**Comment by d3mac123** [comment]
I got it! Thank you very much!!! All I had to do was:
`tCall = (char)((int)(messageBuffer[j + 20] & 0xFF));`
